service: hello-retail-slackbot

provider:
  name: aws
  runtime: nodejs6.10
  iamRoleStatements:
    -  Effect: Allow
       Action:
         - dynamodb:PutItem
       Resource:
         - arn:aws:dynamodb:us-west-2:515126931066:table/fanoutTargets

functions:
  hookstream:
    handler: handler.hookstream
    name: ${opt:stage}-hookstream
    environment:
      HELLO_RETAIL_STAGE: workshop050217
      CORE_STREAM_REGION: us-west-2
      CORE_STREAM_ACCOUNT: 515126931066
      FANOUT_TABLE_NAME: fanoutTargets
    events:
      - http:
          path: slack/hookstream
          method: post